spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}
#  mongodb:
#    client:
#      uri: mongodb://localhost:27017
#      database: fitness_recommendation