spring:
  application:
    name: ai-service
  config:
    import: optional:configserver:http://localhost:8888
#  mongodb:
#    client:
#      uri: mongodb://localhost:27017
#      database: fitness_recommendation