spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_URI}

server:
  port: ${PORT:8080}

services:
  user-service-url: ${USER_SERVICE_URL}
  activity-service-url: ${ACTIVITY_SERVICE_URL}
  ai-service-url: ${AI_SERVICE_URL}

logging:
  level:
    org.springframework.boot.autoconfigure: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info